spring:
 datasource:
  url: jdbc:mysql://localhost:3307/spring_batch?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
  username: root
  password: 1234
 batch:
  jdbc:
   initialize-schema: always

  job:
   names: ${job.name:NONE}
